# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
services:
    rest.helper:
        class: AppBundle\Services\RestHelper
        arguments: ['%timezone%']

    image_payload.converter:
        class: AppBundle\Services\ImagePayloadConverter
        arguments: ['%web_dir%']
